### ISSUE TITLE
Baseline에 대해 질문 있습니다

### ISSUE THREAD

**Issue by HanSeokhyeon** [clovaai/speech_hackathon_2019#1]
Baseline에 feature, architecture, model이 있는데 baseline을 기반으로 수정하는 것이 맞나요?

예를 들어 
1. feature에서 spectrogram 대신 Melspectrogram을 사용 또는 FFT 기반이 아닌 다른 음성특성을 사용.
2. model에서 Seq2seq 모델 대신 다른 음성인식 모델을 사용.

하는 것이 가능한지 궁금합니다!

**Comment by ClovaAIAdmin** [comment]
네. feature와 model 전부 원하는 방법으로 수정해서 만드시면 됩니다.
baseline은 단순히 참고만 하시면 되고,
Pytorch 뿐만 아니라, TensorFlow나 기타 다른 딥러닝 툴을 자유롭게 사용해서 개발하시면 됩니다.
