### ISSUE TITLE
submit이 안되는것 같습니다. 확인 부탁드립니다.

### ISSUE THREAD

**Issue by SaewonY** [clovaai/speech_hackathon_2019#5]
time="2019/09/17 16:18:09.352" level=warning msg="Rate limit exceeded: remained time: 1s"
time="2019/09/17 16:18:09.448" level=fatal msg="Rate limit exceeded"

위와 같은 메세지가 뜨면서 제출이 안되네요.

**Comment by bluebrush** [comment]
@SaewonY 님, 불편을 드려서 죄송합니다. 
rate limit 관련 메시지는 잠시 기다리시면 순차적으로 진행됩니다.

**Comment by SaewonY** [comment]
@bluebrush 감사합니다.
